name: lab 3 create artifact 


on:
  push:
    branches:
     - main 
  pull_request:
    branches:
     - main 


jobs:
  test: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3


      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Pretend build 
      - name: pretend to build 
        run: echo building some sort of an app......

      # upload the build now
      - name: push out hello file
        uses: actions/upload-artifact@v3
        with: 
          name: My-Artifact
          path: Hello2.txt





