name: lab 3 create artifact 


on:
  push:
    branches:
     - main 
  pull_request:
    branches:
     - main 


jobs:
  test: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3


      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Pretend build 
      - name: pretend to build 
        run: echo building some sort of an app......

      # upload the build now
      - name: push out hello file
        uses: actions/upload-artifact@v3
        with: 
          name: My-Artifact
          path: Hello.txt
          if-no-files-found: error 
      
      - name: create another txt file
        uses : actions/upload-artifact@v3
        with:
          name: New-Artifact
          path: artifact.txt 
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: building a test app
        run: echo building a test app.....





